# Generated by Django 6.0.7 on 2026-07-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Asset Assigned', 'Asset Assigned'), ('Asset Returned', 'Asset Returned'), ('Transfer Request', 'Transfer Request'), ('Transfer Approved', 'Transfer Approved'), ('Booking Confirmed', 'Booking Confirmed'), ('Booking Cancelled', 'Booking Cancelled'), ('Booking Reminder', 'Booking Reminder'), ('Maintenance Request', 'Maintenance Request'), ('Maintenance Approved', 'Maintenance Approved'), ('Maintenance Rejected', 'Maintenance Rejected'), ('Audit Assigned', 'Audit Assigned'), ('Audit Discrepancy', 'Audit Discrepancy'), ('Overdue Return', 'Overdue Return'), ('General', 'General')], default='General', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.employee')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
