# Generated by Django 6.0.7 on 2026-07-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Closed', 'Closed')], default='Planned', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_auditors', models.ManyToManyField(related_name='assigned_audits', to='organization.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cycles', to='organization.department')),
            ],
            options={
                'db_table': 'audit_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Missing', 'Missing'), ('Damaged', 'Damaged')], default='Verified', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='assets.asset')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assets', to='organization.employee')),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assets', to='audits.auditcycle')),
            ],
            options={
                'db_table': 'audit_assets',
                'ordering': ['asset__asset_tag'],
                'unique_together': {('audit_cycle', 'asset')},
            },
        ),
    ]
